name: "Build openssl-static 1xx Windows"

on:
  push:
    branches: [ "master" ]
    paths:
      - 'openssl_1xx_versions.yml'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'openssl_1xx_versions.yml'

  workflow_dispatch:

jobs:
  Build-and-upload-openssl-static-1xx: 
      uses: ./.github/workflows/openssl-static_1xx_base_workflow.yml
