name: "Build openssl-static 1xx Windows"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  Build-and-upload-openssl-static-1xx:
    uses: ./.github/workflows/openssl-static_1xx_base_workflow.yml
    with:
      openssl_ver: 1_1_1t
