name: "Build openssl-static 1xx Windows"

on:
  push:
    branches: [ "master" ]
    paths:
      - 'openssl_1xx_versions.yml'
      - '.github/workflows/openssl-static_base_workflow.yml'
      - '.github/workflows/openssl-static_1xx_workflow.yml'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'openssl_1xx_versions.yml'
      - '.github/workflows/openssl-static_base_workflow.yml'
      - '.github/workflows/openssl-static_1xx_workflow.yml'

  workflow_dispatch:

jobs:
  Get-openssl-static-1xx-version:
    runs-on: windows-2022
    outputs:
      openssl_ver: ${{ steps.Read-OpenSSL-version.outputs.openssl_ver }}
      pkg_name: ${{ steps.Read-OpenSSL-version.outputs.pkg_name }}
    steps:
      - uses: actions/checkout@v3
      - id: Read-OpenSSL-version
        name: Read OpenSSL version from file
        shell: pwsh
        run: |
            $openssl_ver=$(Get-Content openssl_1xx_versions.yml | Select-String -Pattern "openssl_ver_1xx" | ForEach-Object { $_.ToString().Split(":")[1].Trim() })
            Write-Output "openssl_ver=${openssl_ver}" >> $env:GITHUB_OUTPUT
            Write-Output "pkg_name=openssl-OpenSSL_${openssl_ver}" >> $env:GITHUB_OUTPUT

  Build-and-upload-openssl-static-1xx:
    needs: Get-openssl-static-1xx-version
    uses: ./.github/workflows/openssl-static_base_workflow.yml
    with:
      openssl_ver: ${{ needs.Get-openssl-static-1xx-version.outputs.openssl_ver }}
      openssl_pkg_name: ${{ needs.Get-openssl-static-1xx-version.outputs.pkg_name }}
      openssl_source_url: https://github.com/openssl/openssl/archive/refs/tags/OpenSSL_${{ needs.Get-openssl-static-1xx-version.outputs.openssl_ver }}.zip