name: "Build openssl-static 3xx Windows"

on:
  push:
    branches: [ "master" ]
    paths:
      - 'openssl_3xx_versions.yml'
      - '.github/workflows/openssl-static_base_workflow.yml'
      - '.github/workflows/openssl-static_3xx_workflow.yml'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'openssl_3xx_versions.yml'
      - '.github/workflows/openssl-static_base_workflow.yml'
      - '.github/workflows/openssl-static_3xx_workflow.yml'

  workflow_dispatch:

jobs:
  Build-and-upload-openssl-static-3xx:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - id: Read-OpenSSL-version
        name: Read OpenSSL version from file
        shell: pwsh
        run: |
            $openssl_ver=$(Get-Content openssl_3xx_versions.yml | Select-String -Pattern "openssl_ver_3xx" | ForEach-Object { $_.ToString().Split(":")[1].Trim() })
            Write-Output "openssl_ver=${openssl_ver}" >> $env:GITHUB_OUTPUT
            Write-Output "pkg_name=openssl-openssl-${openssl_ver}" >> $env:GITHUB_OUTPUT
      - uses: ./.github/workflows/openssl-static_base_workflow.yml
        with:
          openssl_ver: ${{ steps.Read-OpenSSL-version.outputs.openssl_ver }}
          openssl_pkg_name: ${{ steps.Read-OpenSSL-version.outputs.pkg_name }}.zip
          openssl_source_url: https://github.com/openssl/openssl/archive/refs/tags/openssl-${{ steps.Read-OpenSSL-version.outputs.openssl_ver }}.zip