name: "Build openssl-static 3xx Windows"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  Build-and-upload-openssl-static-3xx:
    uses: ./.github/workflows/openssl_static_3xx_base_workflow.yml
    with:
      openssl_ver: 3.1.0
