name: openssl-static-1xx base workflow

on:
  workflow_call:
    inputs:
      openssl_ver:
        required: false
        type: string

jobs:
 
  build-openssl-static-bin:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3

      - id: Read-OpenSSL-version
        name: Read OpenSSL version from file
        shell: pwsh
        run: |
            $openssl_ver=$(Get-Content openssl_versions.yml | Select-String -Pattern "openssl_ver_1xx" | ForEach-Object { $_.ToString().Split(":")[1].Trim() })
            Write-Output "openssl_ver=${openssl_ver}" >> $env:GITHUB_OUTPUT
            Write-Output "pkg_name=openssl-OpenSSL_${openssl_ver}" >> $env:GITHUB_OUTPUT


      - uses: ilammy/setup-nasm@321e6ed62a1fc77024a3bd853deb33645e8b22c4 #v1.4.0
      - uses: ilammy/msvc-dev-cmd@cec98b9d092141f74527d0afa6feb2af698cfe89 #v1.12.1
        with:
          arch: amd64

      - name: Download ${{ steps.Read-OpenSSL-version.outputs.openssl_ver }} source code
        run: aria2c https://github.com/openssl/openssl/archive/refs/tags/OpenSSL_${{ steps.Read-OpenSSL-version.outputs.openssl_ver }}.zip

      - name: Unzip ${{ steps.Read-OpenSSL-version.outputs.openssl_ver }} source code
        run: 7z x ./${{ steps.Read-OpenSSL-version.outputs.pkg_name }}.zip

      - name: Generate makefile
        run: perl Configure VC-WIN64A no-shared no-comp -no-zlib -no-zlib-dynamic
        working-directory: ./${{ steps.Read-OpenSSL-version.outputs.pkg_name }}

      - name: Build openssl-static
        run: nmake
        working-directory: ./${{ steps.Read-OpenSSL-version.outputs.pkg_name }}

      - name: Rename openssl.exe
        run: copy apps\openssl.exe apps\${{ steps.Read-OpenSSL-version.outputs.pkg_name }}.exe
        working-directory: ./${{ steps.Read-OpenSSL-version.outputs.pkg_name }}

      - name: Upload the openssl-${{ steps.Read-OpenSSL-version.outputs.openssl_ver }}
        uses: actions/upload-artifact@v3
        with:
          name: openssl-static-${{ steps.Read-OpenSSL-version.outputs.openssl_ver }}
          path: ./${{ steps.Read-OpenSSL-version.outputs.pkg_name }}/apps/${{ steps.Read-OpenSSL-version.outputs.pkg_name }}.exe
