name: release

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  Get-openssl-static-3xx-version:
    runs-on: windows-2022
    outputs:
      openssl_3xx_ver: ${{ steps.Read-OpenSSL-3xx-version.outputs.openssl_3xx_ver }}
      pkg_3xx_name: ${{ steps.Read-OpenSSL-3xx-version.outputs.pkg_3xx_name }}
    steps:
      - uses: actions/checkout@v3
      - id: Read-OpenSSL-3xx-version
        name: Read OpenSSL 3xx version from file
        shell: pwsh
        run: |
            $openssl_3xx_ver=$(Get-Content openssl_3xx_versions.yml | Select-String -Pattern "openssl_ver_3xx" | ForEach-Object { $_.ToString().Split(":")[1].Trim() })
            Write-Output "openssl_3xx_ver=${openssl_3xx_ver}" >> $env:GITHUB_OUTPUT
            Write-Output "pkg_3xx_name=openssl-openssl-${openssl_3xx_ver}" >> $env:GITHUB_OUTPUT


  Get-openssl-static-1xx-version:
    runs-on: windows-2022
    outputs:
      openssl_1xx_ver: ${{ steps.Read-OpenSSL-1xx-version.outputs.openssl_1xx_ver }}
      pkg_1xx_name: ${{ steps.Read-OpenSSL-1xx-version.outputs.pkg_1xx_name }}
    steps:
      - uses: actions/checkout@v3
      - id: Read-OpenSSL-1xx-version
        name: Read OpenSSL 1xx version from file
        shell: pwsh
        run: |
            $openssl_1xx_ver=$(Get-Content openssl_1xx_versions.yml | Select-String -Pattern "openssl_ver_1xx" | ForEach-Object { $_.ToString().Split(":")[1].Trim() })
            Write-Output "openssl_1xx_ver=${openssl_1xx_ver}" >> $env:GITHUB_OUTPUT
            Write-Output "pkg_1xx_name=openssl-OpenSSL_${openssl_1xx_ver}" >> $env:GITHUB_OUTPUT

  Build-and-upload-openssl-static-1xx:
    needs: Get-openssl-static-1xx-version
    uses: ./.github/workflows/openssl-static_base_workflow.yml
    with:
      openssl_ver: ${{ needs.Get-openssl-static-1xx-version.outputs.openssl_1xx_ver }}
      openssl_pkg_name: ${{ needs.Get-openssl-static-1xx-version.outputs.pkg_1xx_name }}
      openssl_source_url: https://github.com/openssl/openssl/archive/refs/tags/OpenSSL_${{ needs.Get-openssl-static-1xx-version.outputs.openssl_1xx_ver }}.zip

  Build-and-upload-openssl-static-3xx:
    needs: Get-openssl-static-3xx-version
    uses: ./.github/workflows/openssl-static_base_workflow.yml
    with:
      openssl_ver: ${{ needs.Get-openssl-static-3xx-version.outputs.openssl_3xx_ver }}
      openssl_pkg_name: ${{ needs.Get-openssl-static-3xx-version.outputs.pkg_3xx_name }}
      openssl_source_url: https://github.com/openssl/openssl/archive/refs/tags/openssl-${{ needs.Get-openssl-static-3xx-version.outputs.openssl_3xx_ver }}.zip
  
  Build-and-upload-openssl-dll-3xx:
    needs: Get-openssl-static-3xx-version
    uses: ./.github/workflows/openssl-dll_base_workflow.yml
    with:
      openssl_ver: ${{ needs.Get-openssl-static-3xx-version.outputs.openssl_3xx_ver }}
      openssl_pkg_name: ${{ needs.Get-openssl-static-3xx-version.outputs.pkg_3xx_name }}
      openssl_source_url: https://github.com/openssl/openssl/archive/refs/tags/openssl-${{ needs.Get-openssl-static-3xx-version.outputs.openssl_3xx_ver }}.zip

  create-release:
    runs-on: ubuntu-latest
    needs: [Get-openssl-static-1xx-version,Get-openssl-static-3xx-version,Build-and-upload-openssl-static-1xx,Build-and-upload-openssl-static-3xx,Build-and-upload-openssl-dll-3xx]
    steps:
      - name: Download openssl-1xx release file
        uses: actions/download-artifact@v5.0.0
        with:
          name: openssl-static-${{ needs.Get-openssl-static-1xx-version.outputs.openssl_1xx_ver }}

      - name: Download openssl-3xx release file
        uses: actions/download-artifact@v5.0.0
        with:
          name: openssl-static-${{ needs.Get-openssl-static-3xx-version.outputs.openssl_3xx_ver }}
      
      - name: Download openssl-dll-3xx release file
        uses: actions/download-artifact@v5.0.0
        with:
          name: openssl-dll-${{ needs.Get-openssl-static-3xx-version.outputs.openssl_3xx_ver }}

      - name: Release
        uses: softprops/action-gh-release@v2.4.1
        with:
          files: |
            ./openssl-OpenSSL_${{ needs.Get-openssl-static-1xx-version.outputs.openssl_1xx_ver }}.exe
            ./openssl-openssl-${{ needs.Get-openssl-static-3xx-version.outputs.openssl_3xx_ver }}.exe
            ./openssl-dll-${{ needs.Get-openssl-static-3xx-version.outputs.openssl_3xx_ver }}.zip
